### ISSUE TITLE
I get an exception if i try to initialize.

### ISSUE THREAD

**Issue by priskahuber** [Ticketpark/SaferpayJsonApi#1]
If i initialize with same structure as you have in your 1-example-initialize.php but with my credentials, i get the following exception:

Uncaught exception 'Ticketpark\SaferpayJson\Exception\HttpRequestException' with message 'file_get_contents(https://test.saferpay.com/api//Payment/v1/PaymentPage/Initialize): failed to open stream: operation failed' in __MYPATH__\ticketpark\saferpay-json-api\lib\SaferpayJson\Message\Request.php:188

Do you have any ideas?

Best Regards
Priska

**Comment by sprain** [comment]
Quick guess: Your server doesn't allow the use of `file_get_contents()`.
Try using you custom BuzzBrowser (which is already a depencency of this lib) with curl:

```php
$browser = new Buzz\Browser(new Buzz\Client\Curl());

$response = (new InitializeRequest($apiKey, $apiSecret))
    ->setBrowser($browser)
    ->setRequestHeader($requestHeader)
    ->setPayment($payment)
    ->setTerminalId($terminalId)
    ->setReturnUrls($returnUrls)
    ->setNotification($notification)
    ->execute();
```

**Comment by priskahuber** [comment]
i added this and get a new error: 'SSL certificate problem: unable to get local issuer certificate'

**Comment by sprain** [comment]
Make sure, your server is update with latest security standards. This is not specific to this library. Googling the error message will help :)

**Comment by mathmul** [comment]
In my case the problem was that `file_get_contents()` function didn't work on the staging server.

Used this simple script to pinpoint the problem.

```php
<?php

$str = file_get_contents('http://drib.tech');

if($str === false)
{
	print_r(error_get_last());
	die(__FILE__ . __LINE__);
}

echo htmlspecialchars($str);
```

The localhost script reads the URL and prints out it's HTML. Staging server script yields the following (I prettified it here).

```plaintext
Array (
    [type] => 2
    [message] => file_get_contents(http://drib.tech): Failed to open stream: Unable to find the socket transport "ssl" - did you forget to enable it when you configured PHP?
    [file] => /MY_PATH/test-file-get-contents.php
    [line] => 3
)
/MY_PATH/test-file-get-contents.php8
```

`Ctrl + F` with search parameter "openssl" on `phpinfo()` show 3 hits on staging server (two generic, and one stating "OpenSSL support: disabled (install ext/openssl)' while localhost search yields 16 results, 10 of them being in a "openssl" section.

Recompiled PHP with OpenSSL (`--with-openssl` or `--with-openssl-dir`) [and curl and soap which were all missing] fixed the issue.
